# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import warehouse_pb2 as warehouse__pb2


class WarehouseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getData = channel.unary_unary(
                '/WarehouseService/getData',
                request_serializer=warehouse__pb2.WarehouseRequest.SerializeToString,
                response_deserializer=warehouse__pb2.WarehouseData.FromString,
                )


class WarehouseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WarehouseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getData': grpc.unary_unary_rpc_method_handler(
                    servicer.getData,
                    request_deserializer=warehouse__pb2.WarehouseRequest.FromString,
                    response_serializer=warehouse__pb2.WarehouseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WarehouseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WarehouseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WarehouseService/getData',
            warehouse__pb2.WarehouseRequest.SerializeToString,
            warehouse__pb2.WarehouseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
