package tgm.aahuja.warehouse.model;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouse.proto

// Protobuf Java Version: 3.25.1
public final class Warehouse {
  private Warehouse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WarehouseRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WarehouseRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code WarehouseRequest}
   */
  public static final class WarehouseRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WarehouseRequest)
      WarehouseRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WarehouseRequest.newBuilder() to construct.
    private WarehouseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WarehouseRequest() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WarehouseRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Warehouse.internal_static_WarehouseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Warehouse.internal_static_WarehouseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Warehouse.WarehouseRequest.class, Warehouse.WarehouseRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Warehouse.WarehouseRequest)) {
        return super.equals(obj);
      }
      Warehouse.WarehouseRequest other = (Warehouse.WarehouseRequest) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Warehouse.WarehouseRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Warehouse.WarehouseRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Warehouse.WarehouseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Warehouse.WarehouseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Warehouse.WarehouseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Warehouse.WarehouseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Warehouse.WarehouseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Warehouse.WarehouseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Warehouse.WarehouseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Warehouse.WarehouseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Warehouse.WarehouseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Warehouse.WarehouseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Warehouse.WarehouseRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WarehouseRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WarehouseRequest)
        Warehouse.WarehouseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Warehouse.internal_static_WarehouseRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Warehouse.internal_static_WarehouseRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Warehouse.WarehouseRequest.class, Warehouse.WarehouseRequest.Builder.class);
      }

      // Construct using Warehouse.WarehouseRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Warehouse.internal_static_WarehouseRequest_descriptor;
      }

      @java.lang.Override
      public Warehouse.WarehouseRequest getDefaultInstanceForType() {
        return Warehouse.WarehouseRequest.getDefaultInstance();
      }

      @java.lang.Override
      public Warehouse.WarehouseRequest build() {
        Warehouse.WarehouseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Warehouse.WarehouseRequest buildPartial() {
        Warehouse.WarehouseRequest result = new Warehouse.WarehouseRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Warehouse.WarehouseRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Warehouse.WarehouseRequest) {
          return mergeFrom((Warehouse.WarehouseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Warehouse.WarehouseRequest other) {
        if (other == Warehouse.WarehouseRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WarehouseRequest)
    }

    // @@protoc_insertion_point(class_scope:WarehouseRequest)
    private static final Warehouse.WarehouseRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Warehouse.WarehouseRequest();
    }

    public static Warehouse.WarehouseRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WarehouseRequest>
        PARSER = new com.google.protobuf.AbstractParser<WarehouseRequest>() {
      @java.lang.Override
      public WarehouseRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WarehouseRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WarehouseRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Warehouse.WarehouseRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WarehouseDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WarehouseData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string warehouseID = 1;</code>
     * @return The warehouseID.
     */
    java.lang.String getWarehouseID();
    /**
     * <code>string warehouseID = 1;</code>
     * @return The bytes for warehouseID.
     */
    com.google.protobuf.ByteString
        getWarehouseIDBytes();

    /**
     * <code>string warehouseName = 2;</code>
     * @return The warehouseName.
     */
    java.lang.String getWarehouseName();
    /**
     * <code>string warehouseName = 2;</code>
     * @return The bytes for warehouseName.
     */
    com.google.protobuf.ByteString
        getWarehouseNameBytes();

    /**
     * <code>string timestamp = 3;</code>
     * @return The timestamp.
     */
    java.lang.String getTimestamp();
    /**
     * <code>string timestamp = 3;</code>
     * @return The bytes for timestamp.
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>repeated .Product productData = 4;</code>
     */
    java.util.List<Warehouse.Product> 
        getProductDataList();
    /**
     * <code>repeated .Product productData = 4;</code>
     */
    Warehouse.Product getProductData(int index);
    /**
     * <code>repeated .Product productData = 4;</code>
     */
    int getProductDataCount();
    /**
     * <code>repeated .Product productData = 4;</code>
     */
    java.util.List<? extends Warehouse.ProductOrBuilder> 
        getProductDataOrBuilderList();
    /**
     * <code>repeated .Product productData = 4;</code>
     */
    Warehouse.ProductOrBuilder getProductDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code WarehouseData}
   */
  public static final class WarehouseData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WarehouseData)
      WarehouseDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WarehouseData.newBuilder() to construct.
    private WarehouseData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WarehouseData() {
      warehouseID_ = "";
      warehouseName_ = "";
      timestamp_ = "";
      productData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WarehouseData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Warehouse.internal_static_WarehouseData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Warehouse.internal_static_WarehouseData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Warehouse.WarehouseData.class, Warehouse.WarehouseData.Builder.class);
    }

    public static final int WAREHOUSEID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object warehouseID_ = "";
    /**
     * <code>string warehouseID = 1;</code>
     * @return The warehouseID.
     */
    @java.lang.Override
    public java.lang.String getWarehouseID() {
      java.lang.Object ref = warehouseID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        warehouseID_ = s;
        return s;
      }
    }
    /**
     * <code>string warehouseID = 1;</code>
     * @return The bytes for warehouseID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWarehouseIDBytes() {
      java.lang.Object ref = warehouseID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        warehouseID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WAREHOUSENAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object warehouseName_ = "";
    /**
     * <code>string warehouseName = 2;</code>
     * @return The warehouseName.
     */
    @java.lang.Override
    public java.lang.String getWarehouseName() {
      java.lang.Object ref = warehouseName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        warehouseName_ = s;
        return s;
      }
    }
    /**
     * <code>string warehouseName = 2;</code>
     * @return The bytes for warehouseName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWarehouseNameBytes() {
      java.lang.Object ref = warehouseName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        warehouseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object timestamp_ = "";
    /**
     * <code>string timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timestamp = 3;</code>
     * @return The bytes for timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTDATA_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<Warehouse.Product> productData_;
    /**
     * <code>repeated .Product productData = 4;</code>
     */
    @java.lang.Override
    public java.util.List<Warehouse.Product> getProductDataList() {
      return productData_;
    }
    /**
     * <code>repeated .Product productData = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Warehouse.ProductOrBuilder> 
        getProductDataOrBuilderList() {
      return productData_;
    }
    /**
     * <code>repeated .Product productData = 4;</code>
     */
    @java.lang.Override
    public int getProductDataCount() {
      return productData_.size();
    }
    /**
     * <code>repeated .Product productData = 4;</code>
     */
    @java.lang.Override
    public Warehouse.Product getProductData(int index) {
      return productData_.get(index);
    }
    /**
     * <code>repeated .Product productData = 4;</code>
     */
    @java.lang.Override
    public Warehouse.ProductOrBuilder getProductDataOrBuilder(
        int index) {
      return productData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(warehouseID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, warehouseID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(warehouseName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, warehouseName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timestamp_);
      }
      for (int i = 0; i < productData_.size(); i++) {
        output.writeMessage(4, productData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(warehouseID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, warehouseID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(warehouseName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, warehouseName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timestamp_);
      }
      for (int i = 0; i < productData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, productData_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Warehouse.WarehouseData)) {
        return super.equals(obj);
      }
      Warehouse.WarehouseData other = (Warehouse.WarehouseData) obj;

      if (!getWarehouseID()
          .equals(other.getWarehouseID())) return false;
      if (!getWarehouseName()
          .equals(other.getWarehouseName())) return false;
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
      if (!getProductDataList()
          .equals(other.getProductDataList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WAREHOUSEID_FIELD_NUMBER;
      hash = (53 * hash) + getWarehouseID().hashCode();
      hash = (37 * hash) + WAREHOUSENAME_FIELD_NUMBER;
      hash = (53 * hash) + getWarehouseName().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      if (getProductDataCount() > 0) {
        hash = (37 * hash) + PRODUCTDATA_FIELD_NUMBER;
        hash = (53 * hash) + getProductDataList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Warehouse.WarehouseData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Warehouse.WarehouseData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Warehouse.WarehouseData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Warehouse.WarehouseData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Warehouse.WarehouseData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Warehouse.WarehouseData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Warehouse.WarehouseData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Warehouse.WarehouseData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Warehouse.WarehouseData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Warehouse.WarehouseData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Warehouse.WarehouseData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Warehouse.WarehouseData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Warehouse.WarehouseData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WarehouseData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WarehouseData)
        Warehouse.WarehouseDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Warehouse.internal_static_WarehouseData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Warehouse.internal_static_WarehouseData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Warehouse.WarehouseData.class, Warehouse.WarehouseData.Builder.class);
      }

      // Construct using Warehouse.WarehouseData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        warehouseID_ = "";
        warehouseName_ = "";
        timestamp_ = "";
        if (productDataBuilder_ == null) {
          productData_ = java.util.Collections.emptyList();
        } else {
          productData_ = null;
          productDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Warehouse.internal_static_WarehouseData_descriptor;
      }

      @java.lang.Override
      public Warehouse.WarehouseData getDefaultInstanceForType() {
        return Warehouse.WarehouseData.getDefaultInstance();
      }

      @java.lang.Override
      public Warehouse.WarehouseData build() {
        Warehouse.WarehouseData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Warehouse.WarehouseData buildPartial() {
        Warehouse.WarehouseData result = new Warehouse.WarehouseData(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Warehouse.WarehouseData result) {
        if (productDataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            productData_ = java.util.Collections.unmodifiableList(productData_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.productData_ = productData_;
        } else {
          result.productData_ = productDataBuilder_.build();
        }
      }

      private void buildPartial0(Warehouse.WarehouseData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.warehouseID_ = warehouseID_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.warehouseName_ = warehouseName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Warehouse.WarehouseData) {
          return mergeFrom((Warehouse.WarehouseData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Warehouse.WarehouseData other) {
        if (other == Warehouse.WarehouseData.getDefaultInstance()) return this;
        if (!other.getWarehouseID().isEmpty()) {
          warehouseID_ = other.warehouseID_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getWarehouseName().isEmpty()) {
          warehouseName_ = other.warehouseName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (productDataBuilder_ == null) {
          if (!other.productData_.isEmpty()) {
            if (productData_.isEmpty()) {
              productData_ = other.productData_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureProductDataIsMutable();
              productData_.addAll(other.productData_);
            }
            onChanged();
          }
        } else {
          if (!other.productData_.isEmpty()) {
            if (productDataBuilder_.isEmpty()) {
              productDataBuilder_.dispose();
              productDataBuilder_ = null;
              productData_ = other.productData_;
              bitField0_ = (bitField0_ & ~0x00000008);
              productDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductDataFieldBuilder() : null;
            } else {
              productDataBuilder_.addAllMessages(other.productData_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                warehouseID_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                warehouseName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                timestamp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                Warehouse.Product m =
                    input.readMessage(
                        Warehouse.Product.parser(),
                        extensionRegistry);
                if (productDataBuilder_ == null) {
                  ensureProductDataIsMutable();
                  productData_.add(m);
                } else {
                  productDataBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object warehouseID_ = "";
      /**
       * <code>string warehouseID = 1;</code>
       * @return The warehouseID.
       */
      public java.lang.String getWarehouseID() {
        java.lang.Object ref = warehouseID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          warehouseID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string warehouseID = 1;</code>
       * @return The bytes for warehouseID.
       */
      public com.google.protobuf.ByteString
          getWarehouseIDBytes() {
        java.lang.Object ref = warehouseID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          warehouseID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string warehouseID = 1;</code>
       * @param value The warehouseID to set.
       * @return This builder for chaining.
       */
      public Builder setWarehouseID(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        warehouseID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string warehouseID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWarehouseID() {
        warehouseID_ = getDefaultInstance().getWarehouseID();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string warehouseID = 1;</code>
       * @param value The bytes for warehouseID to set.
       * @return This builder for chaining.
       */
      public Builder setWarehouseIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        warehouseID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object warehouseName_ = "";
      /**
       * <code>string warehouseName = 2;</code>
       * @return The warehouseName.
       */
      public java.lang.String getWarehouseName() {
        java.lang.Object ref = warehouseName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          warehouseName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string warehouseName = 2;</code>
       * @return The bytes for warehouseName.
       */
      public com.google.protobuf.ByteString
          getWarehouseNameBytes() {
        java.lang.Object ref = warehouseName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          warehouseName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string warehouseName = 2;</code>
       * @param value The warehouseName to set.
       * @return This builder for chaining.
       */
      public Builder setWarehouseName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        warehouseName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string warehouseName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearWarehouseName() {
        warehouseName_ = getDefaultInstance().getWarehouseName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string warehouseName = 2;</code>
       * @param value The bytes for warehouseName to set.
       * @return This builder for chaining.
       */
      public Builder setWarehouseNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        warehouseName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>string timestamp = 3;</code>
       * @return The timestamp.
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timestamp = 3;</code>
       * @return The bytes for timestamp.
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        timestamp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        timestamp_ = getDefaultInstance().getTimestamp();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 3;</code>
       * @param value The bytes for timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        timestamp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.util.List<Warehouse.Product> productData_ =
        java.util.Collections.emptyList();
      private void ensureProductDataIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          productData_ = new java.util.ArrayList<Warehouse.Product>(productData_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Warehouse.Product, Warehouse.Product.Builder, Warehouse.ProductOrBuilder> productDataBuilder_;

      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public java.util.List<Warehouse.Product> getProductDataList() {
        if (productDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(productData_);
        } else {
          return productDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public int getProductDataCount() {
        if (productDataBuilder_ == null) {
          return productData_.size();
        } else {
          return productDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Warehouse.Product getProductData(int index) {
        if (productDataBuilder_ == null) {
          return productData_.get(index);
        } else {
          return productDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Builder setProductData(
          int index, Warehouse.Product value) {
        if (productDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductDataIsMutable();
          productData_.set(index, value);
          onChanged();
        } else {
          productDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Builder setProductData(
          int index, Warehouse.Product.Builder builderForValue) {
        if (productDataBuilder_ == null) {
          ensureProductDataIsMutable();
          productData_.set(index, builderForValue.build());
          onChanged();
        } else {
          productDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Builder addProductData(Warehouse.Product value) {
        if (productDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductDataIsMutable();
          productData_.add(value);
          onChanged();
        } else {
          productDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Builder addProductData(
          int index, Warehouse.Product value) {
        if (productDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductDataIsMutable();
          productData_.add(index, value);
          onChanged();
        } else {
          productDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Builder addProductData(
          Warehouse.Product.Builder builderForValue) {
        if (productDataBuilder_ == null) {
          ensureProductDataIsMutable();
          productData_.add(builderForValue.build());
          onChanged();
        } else {
          productDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Builder addProductData(
          int index, Warehouse.Product.Builder builderForValue) {
        if (productDataBuilder_ == null) {
          ensureProductDataIsMutable();
          productData_.add(index, builderForValue.build());
          onChanged();
        } else {
          productDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Builder addAllProductData(
          java.lang.Iterable<? extends Warehouse.Product> values) {
        if (productDataBuilder_ == null) {
          ensureProductDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, productData_);
          onChanged();
        } else {
          productDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Builder clearProductData() {
        if (productDataBuilder_ == null) {
          productData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          productDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Builder removeProductData(int index) {
        if (productDataBuilder_ == null) {
          ensureProductDataIsMutable();
          productData_.remove(index);
          onChanged();
        } else {
          productDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Warehouse.Product.Builder getProductDataBuilder(
          int index) {
        return getProductDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Warehouse.ProductOrBuilder getProductDataOrBuilder(
          int index) {
        if (productDataBuilder_ == null) {
          return productData_.get(index);  } else {
          return productDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public java.util.List<? extends Warehouse.ProductOrBuilder> 
           getProductDataOrBuilderList() {
        if (productDataBuilder_ != null) {
          return productDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(productData_);
        }
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Warehouse.Product.Builder addProductDataBuilder() {
        return getProductDataFieldBuilder().addBuilder(
            Warehouse.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public Warehouse.Product.Builder addProductDataBuilder(
          int index) {
        return getProductDataFieldBuilder().addBuilder(
            index, Warehouse.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product productData = 4;</code>
       */
      public java.util.List<Warehouse.Product.Builder> 
           getProductDataBuilderList() {
        return getProductDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Warehouse.Product, Warehouse.Product.Builder, Warehouse.ProductOrBuilder> 
          getProductDataFieldBuilder() {
        if (productDataBuilder_ == null) {
          productDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Warehouse.Product, Warehouse.Product.Builder, Warehouse.ProductOrBuilder>(
                  productData_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          productData_ = null;
        }
        return productDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WarehouseData)
    }

    // @@protoc_insertion_point(class_scope:WarehouseData)
    private static final Warehouse.WarehouseData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Warehouse.WarehouseData();
    }

    public static Warehouse.WarehouseData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WarehouseData>
        PARSER = new com.google.protobuf.AbstractParser<WarehouseData>() {
      @java.lang.Override
      public WarehouseData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WarehouseData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WarehouseData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Warehouse.WarehouseData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string productID = 1;</code>
     * @return The productID.
     */
    java.lang.String getProductID();
    /**
     * <code>string productID = 1;</code>
     * @return The bytes for productID.
     */
    com.google.protobuf.ByteString
        getProductIDBytes();

    /**
     * <code>string productName = 2;</code>
     * @return The productName.
     */
    java.lang.String getProductName();
    /**
     * <code>string productName = 2;</code>
     * @return The bytes for productName.
     */
    com.google.protobuf.ByteString
        getProductNameBytes();

    /**
     * <code>string productCategory = 3;</code>
     * @return The productCategory.
     */
    java.lang.String getProductCategory();
    /**
     * <code>string productCategory = 3;</code>
     * @return The bytes for productCategory.
     */
    com.google.protobuf.ByteString
        getProductCategoryBytes();

    /**
     * <code>int32 productQuantity = 4;</code>
     * @return The productQuantity.
     */
    int getProductQuantity();
  }
  /**
   * Protobuf type {@code Product}
   */
  public static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      productID_ = "";
      productName_ = "";
      productCategory_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Product();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Warehouse.internal_static_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Warehouse.internal_static_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Warehouse.Product.class, Warehouse.Product.Builder.class);
    }

    public static final int PRODUCTID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object productID_ = "";
    /**
     * <code>string productID = 1;</code>
     * @return The productID.
     */
    @java.lang.Override
    public java.lang.String getProductID() {
      java.lang.Object ref = productID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productID_ = s;
        return s;
      }
    }
    /**
     * <code>string productID = 1;</code>
     * @return The bytes for productID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductIDBytes() {
      java.lang.Object ref = productID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object productName_ = "";
    /**
     * <code>string productName = 2;</code>
     * @return The productName.
     */
    @java.lang.Override
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      }
    }
    /**
     * <code>string productName = 2;</code>
     * @return The bytes for productName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTCATEGORY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object productCategory_ = "";
    /**
     * <code>string productCategory = 3;</code>
     * @return The productCategory.
     */
    @java.lang.Override
    public java.lang.String getProductCategory() {
      java.lang.Object ref = productCategory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productCategory_ = s;
        return s;
      }
    }
    /**
     * <code>string productCategory = 3;</code>
     * @return The bytes for productCategory.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductCategoryBytes() {
      java.lang.Object ref = productCategory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productCategory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTQUANTITY_FIELD_NUMBER = 4;
    private int productQuantity_ = 0;
    /**
     * <code>int32 productQuantity = 4;</code>
     * @return The productQuantity.
     */
    @java.lang.Override
    public int getProductQuantity() {
      return productQuantity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productCategory_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productCategory_);
      }
      if (productQuantity_ != 0) {
        output.writeInt32(4, productQuantity_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, productID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productCategory_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productCategory_);
      }
      if (productQuantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, productQuantity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Warehouse.Product)) {
        return super.equals(obj);
      }
      Warehouse.Product other = (Warehouse.Product) obj;

      if (!getProductID()
          .equals(other.getProductID())) return false;
      if (!getProductName()
          .equals(other.getProductName())) return false;
      if (!getProductCategory()
          .equals(other.getProductCategory())) return false;
      if (getProductQuantity()
          != other.getProductQuantity()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductID().hashCode();
      hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProductName().hashCode();
      hash = (37 * hash) + PRODUCTCATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getProductCategory().hashCode();
      hash = (37 * hash) + PRODUCTQUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getProductQuantity();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Warehouse.Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Warehouse.Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Warehouse.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Warehouse.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Warehouse.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Warehouse.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Warehouse.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Warehouse.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Warehouse.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Warehouse.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Warehouse.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Warehouse.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Warehouse.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Product)
        Warehouse.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Warehouse.internal_static_Product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Warehouse.internal_static_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Warehouse.Product.class, Warehouse.Product.Builder.class);
      }

      // Construct using Warehouse.Product.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        productID_ = "";
        productName_ = "";
        productCategory_ = "";
        productQuantity_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Warehouse.internal_static_Product_descriptor;
      }

      @java.lang.Override
      public Warehouse.Product getDefaultInstanceForType() {
        return Warehouse.Product.getDefaultInstance();
      }

      @java.lang.Override
      public Warehouse.Product build() {
        Warehouse.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Warehouse.Product buildPartial() {
        Warehouse.Product result = new Warehouse.Product(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Warehouse.Product result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.productID_ = productID_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.productName_ = productName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.productCategory_ = productCategory_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.productQuantity_ = productQuantity_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Warehouse.Product) {
          return mergeFrom((Warehouse.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Warehouse.Product other) {
        if (other == Warehouse.Product.getDefaultInstance()) return this;
        if (!other.getProductID().isEmpty()) {
          productID_ = other.productID_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getProductName().isEmpty()) {
          productName_ = other.productName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getProductCategory().isEmpty()) {
          productCategory_ = other.productCategory_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getProductQuantity() != 0) {
          setProductQuantity(other.getProductQuantity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                productID_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                productName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                productCategory_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                productQuantity_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object productID_ = "";
      /**
       * <code>string productID = 1;</code>
       * @return The productID.
       */
      public java.lang.String getProductID() {
        java.lang.Object ref = productID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productID = 1;</code>
       * @return The bytes for productID.
       */
      public com.google.protobuf.ByteString
          getProductIDBytes() {
        java.lang.Object ref = productID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productID = 1;</code>
       * @param value The productID to set.
       * @return This builder for chaining.
       */
      public Builder setProductID(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        productID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string productID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductID() {
        productID_ = getDefaultInstance().getProductID();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string productID = 1;</code>
       * @param value The bytes for productID to set.
       * @return This builder for chaining.
       */
      public Builder setProductIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        productID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object productName_ = "";
      /**
       * <code>string productName = 2;</code>
       * @return The productName.
       */
      public java.lang.String getProductName() {
        java.lang.Object ref = productName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productName = 2;</code>
       * @return The bytes for productName.
       */
      public com.google.protobuf.ByteString
          getProductNameBytes() {
        java.lang.Object ref = productName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productName = 2;</code>
       * @param value The productName to set.
       * @return This builder for chaining.
       */
      public Builder setProductName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        productName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string productName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductName() {
        productName_ = getDefaultInstance().getProductName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string productName = 2;</code>
       * @param value The bytes for productName to set.
       * @return This builder for chaining.
       */
      public Builder setProductNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        productName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object productCategory_ = "";
      /**
       * <code>string productCategory = 3;</code>
       * @return The productCategory.
       */
      public java.lang.String getProductCategory() {
        java.lang.Object ref = productCategory_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productCategory_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productCategory = 3;</code>
       * @return The bytes for productCategory.
       */
      public com.google.protobuf.ByteString
          getProductCategoryBytes() {
        java.lang.Object ref = productCategory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productCategory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productCategory = 3;</code>
       * @param value The productCategory to set.
       * @return This builder for chaining.
       */
      public Builder setProductCategory(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        productCategory_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string productCategory = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductCategory() {
        productCategory_ = getDefaultInstance().getProductCategory();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string productCategory = 3;</code>
       * @param value The bytes for productCategory to set.
       * @return This builder for chaining.
       */
      public Builder setProductCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        productCategory_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int productQuantity_ ;
      /**
       * <code>int32 productQuantity = 4;</code>
       * @return The productQuantity.
       */
      @java.lang.Override
      public int getProductQuantity() {
        return productQuantity_;
      }
      /**
       * <code>int32 productQuantity = 4;</code>
       * @param value The productQuantity to set.
       * @return This builder for chaining.
       */
      public Builder setProductQuantity(int value) {

        productQuantity_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 productQuantity = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductQuantity() {
        bitField0_ = (bitField0_ & ~0x00000008);
        productQuantity_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Product)
    }

    // @@protoc_insertion_point(class_scope:Product)
    private static final Warehouse.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Warehouse.Product();
    }

    public static Warehouse.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @java.lang.Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Warehouse.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WarehouseRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WarehouseRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WarehouseData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WarehouseData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017warehouse.proto\"\036\n\020WarehouseRequest\022\n\n" +
      "\002id\030\001 \001(\t\"m\n\rWarehouseData\022\023\n\013warehouseI" +
      "D\030\001 \001(\t\022\025\n\rwarehouseName\030\002 \001(\t\022\021\n\ttimest" +
      "amp\030\003 \001(\t\022\035\n\013productData\030\004 \003(\0132\010.Product" +
      "\"c\n\007Product\022\021\n\tproductID\030\001 \001(\t\022\023\n\013produc" +
      "tName\030\002 \001(\t\022\027\n\017productCategory\030\003 \001(\t\022\027\n\017" +
      "productQuantity\030\004 \001(\0052B\n\020WarehouseServic" +
      "e\022.\n\007getData\022\021.WarehouseRequest\032\016.Wareho" +
      "useData\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WarehouseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WarehouseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WarehouseRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_WarehouseData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WarehouseData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WarehouseData_descriptor,
        new java.lang.String[] { "WarehouseID", "WarehouseName", "Timestamp", "ProductData", });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "ProductID", "ProductName", "ProductCategory", "ProductQuantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
